Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2024
Var
// Seção de Declarações das variáveis 

 r: real
 area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreva("Digite o valor do raio do circulo ")
 leia(r)
 
 area <- Pi * Exp(r, 2)
 escreva("Area = ", area:8:3)
 

Fimalgoritmo