Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/01/2025
Var
 x, y :inteiro

Inicio

 escreval("Digite dois números: ")
 leia(x)
 leia(y)
 
 enquanto x <> y faca
  se x < y entao
   escreval("Crescente")
  senao
   escreval("Decresecente")
  fimse
  
  escreval("Digite outros dois numeros: ")
  leia(x)
  leia(y)
  
 fimenquanto

Fimalgoritmo