Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2024
Var
// Seção de Declarações das variáveis 

 x, y, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreva("Digite o valor de x: ")
 leia(x)
 
 escreva("Digite o valor de y: ")
 leia(y)
 
 soma <- x + y
 
 escreva("Soma = ", soma )

Fimalgoritmo